//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssuesTracker.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBuser
    {
        public int userId { get; set; }
        public string personName { get; set; }
        public string personEmail { get; set; }
        public string personRole { get; set; }
        public string userName { get; set; }
        public string assignedProject { get; set; }
        public Nullable<System.DateTime> registeredDate { get; set; }
        public byte[] personPhoto { get; set; }
    }
}
